name: default
channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- msprime >=1.3.3,<2
- tskit >=0.6.0,<0.7
- numpy >=2.2.3,<3
- jupyterlab >=4.3.5,<5
- demesdraw >=0.4.0,<0.5
- snakemake >=8.29.3,<9
- tszip >=0.2.5,<0.3
- snakefmt >=0.10.2,<0.11
- black >=24.10.0,<25

