[project]
authors = ["Curro Campuzano <campuzanocurrogmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "invasion-Ne"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
msprime = ">=1.3.3,<2"
tskit = ">=0.6.0,<0.7"
numpy = ">=2.2.3,<3"
jupyterlab = ">=4.3.5,<5"
