[package]
name = "ld_binning"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
indicatif = "0.17.11"
rand = "0.9.1"
rand_chacha = "0.9.0"
rust-htslib = "0.49.0"
