# --- example_config.yaml ---
input-dir: "data" # directory with input files per chromosome, that are "chrom.vcf" "chrom.hapmap" "chrom.mask.bed"
chunk-size: 1e6 # target size in base pairs for each singer run
max-missing: 0.975 # ignore chunks with more than this proportion of missing bases
mutation-rate: 1e-8 # per base per generation mutation rate
recombination-rate: 1e-8 # per base per generation recombination rate, ignored if hapmap is present
polarised: False # are variants polarised so that the reference state is ancestral
mcmc-samples: 100 # number of MCMC samples (each sample is a tree sequence)
mcmc-thin: 10 # thinning interval between MCMC samples
mcmc-burnin: 0.2 # proportion of initial samples discarded when computing plots of statistics
mcmc-resumes: 1000 # maximum number of times to try to resume MCMC on error at a given iteration
coalrate-epochs: 25 # number of time intervals within which to calculate coalescence rates
stratify-by: None # column in metadata to stratify statistics by, or None (TODO: not implemented)
random-seed: 1 # random seed
singer-binary: "resources/singer-0.1.8-beta-linux-x86_64/singer" # this version is needed for "-resume" flag (TODO: automatically fetch from SINGER repo)
