name: default
channels:
    - conda-forge
    - bioconda
    - r
dependencies:
    - msprime >=1.3.3,<2
    - tskit >=0.6.0,<0.7
    - jupyterlab >=4.3.5,<5
    - demesdraw >=0.4.0,<0.5
    - snakemake >=8.29.3,<9
    - tszip >=0.2.5,<0.3
    - snakefmt >=0.10.2,<0.11
    - black >=24.10.0,<25
    - bcftools >=1.21,<2
    - tabix >=1.11,<2
    - vcftools >=0.1.16,<0.2
    - plink >=1.90b7.7,<2
    - r-tidyverse >=2.0.0,<3
    - numba >=0.61.0,<0.62
    - scikit-allel >=1.3.13,<2
    - numpy >=2.1.3,<3