name: default
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - msprime >=1.3.4,<2
    - jupyterlab >=4.4.2,<5
    - bcftools >=1.21,<2
    - simpy >=4.1.1,<5
    - ipython >=9.2.0,<10
    - sympy >=1.14.0,<2
    - slim >=5.0,<6
    - pyslim >=1.0.4,<2
    - snakemake >=9.3.4,<10
    - pandas >=2.2.3,<3
    - plink >=1.90b7.7,<2
    - snakefmt >=0.11.0,<0.12
    - numba >=0.61.2,<0.62
    - pandas-plink >=2.3.2,<3
    - scipy >=1.15.2,<2
    - matplotlib >=3.10.3,<4
    - scikit-learn >=1.6.1,<2
    - tskit >=0.6.3,<0.7
    - demesdraw >=0.4.0,<0.5
    - tszip >=0.2.5,<0.3
    - black >=24.10.0,<25
    - r-tidyverse >=2.0.0,<3
    - numpy >=2.2.5,<3
    - arviz >=0.21.0,<0.22
    - snakemake-executor-plugin-slurm >=1.2.5,<2
    - cmdstanpy >=1.2.5,<2
    - pymc >=5.22,<6
    - emcee >=3.1.6,<4
