name: default
channels:
- conda-forge
- bioconda
- r
dependencies:
- msprime >=1.3.3,<2
- pandas >=2.2.3,<3
- pyyaml >=6.0.2,<7
- bcftools >=1.21,<2
- plink >=1.90b7.7,<2
- snakemake >=9.1.3,<10
- snakefmt >=0.11.0,<0.12
- pandas-plink >=2.3.1,<3
- numba >=0.61.0,<0.62
- scipy >=1.15.2,<2
- matplotlib >=3.10.1,<4
- scikit-learn >=1.6.1,<2
- tskit >=0.6.0,<0.7
- jupyterlab >=4.3.6,<5
- demesdraw >=0.4.0,<0.5
- tszip >=0.2.5,<0.3
- black >=24.10.0,<25
- r-tidyverse >=2.0.0,<3
- numpy >=2.1.3,<3
- cyvcf2 >=0.31.1,<0.32
- arviz >=0.21.0,<0.22